server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: dew123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # for dev; later use validate/migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "super-secret-jwt-key-change-in-prod-super-secret-jwt-key-12345"
  expiration-ms: 3600000  # 1 hour
